print("Welcome to Zootopia")
first_name=input("Enter your any element from periodic table\n")
print(first_name)
last_name =input("Enter your favourite animal,bird or fish\n")
print(last_name)
print("Your in game name is "+first_name+"_"+last_name) 